"""initial schema

Revision ID: d2550116f6ce
Revises: 
Create Date: 2026-06-20 00:30:35.933046
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd2550116f6ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('t', sa.Text(), nullable=False),
    sa.Column('ts', sa.String(length=50), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_job_id'), ['job_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t', sa.String(length=500), nullable=False),
    sa.Column('client', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('lvl', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('src', sa.String(length=100), nullable=False),
    sa.Column('skill', sa.String(length=100), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('ask', sa.Text(), nullable=True),
    sa.Column('draft', sa.Text(), nullable=True),
    sa.Column('esc', sa.Boolean(), nullable=True),
    sa.Column('est', sa.Integer(), nullable=True),
    sa.Column('last_ag', sa.String(length=500), nullable=True),
    sa.Column('last_ts', sa.String(length=50), nullable=True),
    sa.Column('result_label', sa.String(length=200), nullable=True),
    sa.Column('result_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_client'), ['client'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_lvl'), ['lvl'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_t'), ['t'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_t'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_lvl'))
        batch_op.drop_index(batch_op.f('ix_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_client'))

    op.drop_table('jobs')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_job_id'))
        batch_op.drop_index(batch_op.f('ix_activity_id'))

    op.drop_table('activity')
    # ### end Alembic commands ###
